services:
  postgres:
    image: postgres:15
    container_name: optio-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drift_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # შეიცვალა აქ

  redis:
    image: redis:7
    container_name: optio-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: optio-mq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
